server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: data-archiver
  main:
    banner-mode: off
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${BOT_EMAIL}
    password: ${BOT_EMAIL_PASSWORD}
    protocol: smtp

  threads:
    virtual:
      enabled: true

admin:
  mail:
    to:
      address: ${ADMIN_EMAIL}


storage:
  bucket: ${BUCKET_NAME}

db:
  file:
    location: ${DB_FILE_PATH}
    name: ${BACKUP_FILE_NAME}


date:
  format: yyyy_MM_dd

bkadmin:
  name: ${ADMIN_NAME}


LOGS: ${LOGS}
KEY_DIR: ${KEY_DIR}

base:
  bucket:
    folder: ${BASE_BACKUP_FOLDER}
